### ISSUE TITLE
Make Chunks of Federated Users

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/broadcast-transformer#2]
- [ ] Make chunks of federated users - 50(configurable) users per xmsg And divide xmsgs as such.

**Comment by karntrehan** [comment]
DTO changes leading to errors. Will need to fix that first.

**Comment by karntrehan** [comment]
Dev done.

**Comment by karntrehan** [comment]
To be deployed today on production.

**Comment by pankajjangid05** [comment]
PR is created @surabhi-mahawar @chinmoy12c Can you please review it.

- https://github.com/samagra-comms/orchestrator/pull/33

**Comment by chinmoy12c** [comment]
> PR is created @surabhi-mahawar @chinmoy12c Can you please review it.
> 
>     * [[Feature] - Sending Notifications in Chunks orchestrator#33](https://github.com/samagra-comms/orchestrator/pull/33)

I've requested a few changes on the PR @pankajjangid05 , please have a look.

**Comment by pankajjangid05** [comment]
Changes are done as you commited on PR @chinmoy12c, Please have a look. 

> * https://github.com/samagra-comms/orchestrator/pull/33

**Comment by pankajjangid05** [comment]
Code is deployed on production server

**Comment by karntrehan** [comment]
Trigger a notification to segment 1 to ensure this is working as expected.
