### ISSUE TITLE
Reduce Logs in Broadcast Transformer

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/broadcast-transformer#5]
Description :

1. Add meaningful info, debug, warn, error logs, and line number with log level.
2. Remove irrelevant logs
3. Add XMessage print logs when XMessage is sent to Kafka topic
4. Add message print logs which will be sent to user from Netcore/Gupshup/PWA/firebase
5. Add logback-spring.xml file with a valid log format.

**Comment by chinmoy12c** [comment]
Logs have been revamped to suit our debugging needs and are deployed on servers. Closing this issue now.
