### ISSUE TITLE
Merge release-v2.0.0 in Development and Deploy

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/broadcast-transformer#7]
PR - https://github.com/samagra-comms/broadcast-transformer/pull/6

**Comment by pankajjangid05** [comment]
- [ ] Merge code in the development branch
- [ ] Code deployed on stage server (CSM)

**Comment by chinmoy12c** [comment]
Health API has not been updated on this service yet.

**Comment by chinmoy12c** [comment]
Here is the updated code for health API:
https://github.com/samagra-comms/broadcast-transformer/pull/10
